### ISSUE TITLE
New Issue Template

### ISSUE THREAD

**Issue by jonathanwalkerscripts** [jonathanwalkerscripts/OppChasers#17]
## Environment (Devices, Browser, User type)
Device: macOS Catalina - Version 10.15.7
Browser: Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
User type: User

## Description
This is where you will type a short description of the issue. It is a general summary of issue, and should include any important details not listed elsewhere in the report.

## Expected Behavior
This is where you will enter what you expected to happen before the issue occurred. It helps give context to the mindset of the tester/user, and how they believed the application would behave.

## Actual Behavior
This is where you will enter a short summary of what actually happened when you executed your test. This should be some sort of 'Unexpected Behavior', which is different from the 'Expected Behavior' listed in the previous section.

## Steps to Reproduce Issue
This is where you will give step-by-step instructions on how to make this bug happen. It's important to be descriptive, and make sure you don't leave out any steps. Somebody that has never used the application should be able to follow your steps and reproduce this issue.

1. Navigate to (Website Name) at (Website Link)
2. Log in using your Company credentials provided by @jonathanwalkerscripts 
3. Click the green button on the far right side of the Navbar to open the 'Edit Listing' page for a listing you've already created
4. In the job description field, type a description using punctuation such as quotations " periods . commas , and slashes /
5. Click the green 'Save' button to save the listing you just edited
6. The page should refresh and display the listing, including the changes you've made
7. Notice that the saved text has additional slashes not included by the user

## Screenshots

![SlashesBeforeOnward](https://user-images.githubusercontent.com/53547697/108571068-31d2ff00-72c4-11eb-93f7-c2d15c716020.png)
![SlashesAfterOnward](https://user-images.githubusercontent.com/53547697/108571075-35668600-72c4-11eb-9eab-146c20104d24.png)

## Notes
The screenshots show the text before and after saving (additional slashes in after). Team confirmed the bug occurs on both Windows and Mac OS.

**Comment by brianifoster** [comment]
## Environment (Devices, Browser, User type)
Device: macOS Catalina - Version 10.15.7
Browser: Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
User type: User


## Description
This is where you will type a short description of the issue. It is a general summary of issue, and should include any important details not listed elsewhere in the report.

## Expected Behavior
This is where you will enter what you expected to happen before the issue occurred. It helps give context to the mindset of the tester/user, and how they believed the application would behave.

## Actual Behavior
This is where you will enter a short summary of what actually happened when you executed your test. This should be some sort of 'Unexpected Behavior', which is different from the 'Expected Behavior' listed in the previous section.

## Steps to Reproduce Issue
This is where you will give step-by-step instructions on how to make this bug happen. It's important to be descriptive, and make sure you don't leave out any steps. Somebody that has never used the application should be able to follow your steps and reproduce this issue.

1. Navigate to (Website Name) at (Website Link)
2. Log in using your Company credentials provided by @jonathanwalkerscripts 
3. Click the green button on the far right side of the Navbar to open the 'Edit Listing' page for a listing you've already created
4. In the job description field, type a description using punctuation such as quotations " periods . commas , and slashes /
5. Click the green 'Save' button to save the listing you just edited
6. The page should refresh and display the listing, including the changes you've made
7. Notice that the saved text has additional slashes not included by the user

## Screenshots


![SlashesBeforeOnward](https://user-images.githubusercontent.com/53547697/108571068-31d2ff00-72c4-11eb-93f7-c2d15c716020.png)
![SlashesAfterOnward](https://user-images.githubusercontent.com/53547697/108571075-35668600-72c4-11eb-9eab-146c20104d24.png)





## Notes
The screenshots show the text before and after saving (additional slashes in after). Team confirmed the bug occurs on both Windows and Mac OS.
